# Generated by Django 3.0.2 on 2020-04-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200406_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='due',
        ),
    ]
