# Generated by Django 3.0.2 on 2020-04-08 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('due', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.URLField()),
                ('assignment_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
            ],
        ),
    ]
