# Generated by Django 3.0.2 on 2020-04-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_canvasuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasuser',
            name='APIkey',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
