# Generated by Django 3.0.2 on 2020-04-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20200410_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasuser',
            name='img',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='canvasuser',
            name='name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
